import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create(theme => ({
  content: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    padding: theme.rf(16),
    borderRadius: theme.rf(28),
    overflow: 'hidden',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconCircle: {
    width: theme.rf(44),
    height: theme.rf(44),
    borderRadius: theme.rf(24),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.white,
  },
  metaRow: {
    flexDirection: 'row',
    gap: theme.rf(8),
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.rf(4),
    height: theme.rf(36),
    paddingHorizontal: theme.rf(12),
    borderRadius: theme.rf(24),
    backgroundColor: '#FFFFFF99',
  },
  metaText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(10),
    fontWeight: '600',
    letterSpacing: -0.11,
    color: theme.colors.primary50,
  },
  category: {
    fontFamily: theme.typography.primary.normal,
    fontSize: theme.rf(14),
    fontWeight: '400',
    letterSpacing: -0.154,
    color: '#9881B3',
    marginTop: theme.rf(16),
  },
  title: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(28),
    fontWeight: '500',
    letterSpacing: -0.308,
    color: '#010000',
    marginTop: theme.rf(4),
  },
  illoWrap: {
    flex: 1,
    marginTop: theme.rf(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  illoBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  startBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.white,
    height: theme.rf(60),
    borderRadius: theme.rf(64),
    paddingLeft: theme.rf(22),
    paddingRight: theme.rf(10),
    marginTop: theme.rf(8),
  },
  startText: {
    fontFamily: theme.typography.primary.medium,
    fontSize: theme.rf(15),
    color: theme.colors.primary,
  },
  playCircle: {
    width: theme.rf(40),
    height: theme.rf(40),
    borderRadius: theme.rf(20),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  playIcon: {
    marginLeft: 2,
  },
}));
