import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography } from '@/theme';

export const styles = StyleSheet.create({
  screenBg: {
    flex: 1,
    backgroundColor: colors.palette.white,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerContainer: {
    backgroundColor: colors.palette.mint,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  backBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  headerHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTextCol: {
    flex: 1,
    paddingRight: 10,
  },
  lettersCategoryText: {
    fontFamily: typography.primary.bold,
    fontSize: 14,
    color: '#8A91D0',
    letterSpacing: 0.5,
  },
  lettersMainHeading: {
    fontFamily: typography.primary.bold,
    fontSize: 26,
    color: colors.palette.primary,
    lineHeight: 33,
    marginTop: 4,
  },
  capsuleRow: {
    flexDirection: 'row',
    marginTop: 16,
  },
  metaCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    marginRight: 8,
  },
  metaIcon: {
    marginRight: 4,
  },
  metaText: {
    fontFamily: typography.primary.medium,
    fontSize: 11,
    color: colors.palette.primary,
  },
  illustrateWrapper: {
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  aiBuddyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 24,
    marginTop: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.55)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  aiAvatarWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  aiSubtitle: {
    fontFamily: typography.primary.medium,
    fontSize: 11,
    color: 'rgba(28, 39, 76, 0.5)',
  },
  aiTitle: {
    fontFamily: typography.primary.bold,
    fontSize: 15,
    color: colors.palette.primary,
    marginTop: 2,
  },
  timelineSectionContainer: {
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  timelineRow: {
    flexDirection: 'row',
    minHeight: 130,
  },
  cardCol: {
    flex: 1,
    marginLeft: 12,
    paddingBottom: 16,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(28, 39, 76, 0.4)',
  },
  modalContentCard: {
    width: Dimensions.get('window').width * 0.82,
    padding: 24,
    borderRadius: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  modalCloseBtn: {
    position: 'absolute',
    top: 20,
    right: 20,
    padding: 4,
  },
  giantLetterCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: colors.palette.neutral100,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 20,
  },
  giantLetterText: {
    fontFamily: typography.primary.bold,
    fontSize: 60,
    color: colors.palette.primary,
  },
  modalLessonTitle: {
    fontFamily: typography.primary.bold,
    fontSize: 22,
    color: colors.palette.primary,
    textAlign: 'center',
  },
  modalLessonDesc: {
    fontFamily: typography.primary.normal,
    fontSize: 14,
    color: 'rgba(28, 39, 76, 0.65)',
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 20,
  },
  modalStatsRow: {
    flexDirection: 'row',
    marginTop: 20,
  },
  modalStatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    marginHorizontal: 6,
  },
  modalStatText: {
    fontFamily: typography.primary.bold,
    fontSize: 12,
    color: colors.palette.primary,
  },
  modalActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.palette.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    marginTop: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  modalActionIcon: {
    marginRight: 8,
  },
  modalActionBtnText: {
    fontFamily: typography.primary.bold,
    fontSize: 14,
    color: colors.palette.neutral100,
  },
  cardContainer: {
    padding: 16,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 1.5,
  },
  fadedCard: {
    opacity: 0.45,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontFamily: typography.primary.bold,
    fontSize: 18,
    color: colors.palette.primary,
  },
  durationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeClockIcon: {
    marginRight: 4,
  },
  durationText: {
    fontFamily: typography.primary.medium,
    fontSize: 11,
    color: colors.palette.primary,
  },
  cardDescription: {
    fontFamily: typography.primary.normal,
    fontSize: 13,
    color: 'rgba(28, 39, 76, 0.6)',
    marginTop: 8,
    lineHeight: 18,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 12,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.palette.neutral100,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  playButtonText: {
    fontFamily: typography.primary.bold,
    fontSize: 12,
    color: colors.palette.primary,
    marginRight: 6,
  },
  playIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.palette.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIcon: {
    marginLeft: 1.5,
  },
});
